### ISSUE TITLE
Can we slow down the dragger speed anyhow ?

### ISSUE THREAD

**Issue by MrShaikh1357** [ruisoftware/jquery-rsSliderLens#11]
Is it possible to slow down the dragger speed ?

**Comment by ruisoftware** [comment]
I am not really sure what you mean by that.
If you are asking to slowdown the handle animation, you can do that in the plugin constructor.
```
  handle: {
    animation: 500
  }
```
By default, the handle takes 100ms to move from the far left to the right (or vice-versa).

In this [CodePen](https://codepen.io/ruisoftware/pen/VwmLGZj?editors=1111), it was changed to 500ms.
